### ISSUE TITLE
Got "received 500 HTTP response" and other errors

### ISSUE THREAD

**Issue by RasyiidWho** [kerray/RedditToTwitterAndFacebook#5]
I try to run your script, and I got received 500 HTTP response and others error. I try to use both python (2 and 3) also trying on both OS (CentOS 7.6 and Windows 10), but problem still not solved.

Here's is the error:

**Python2:**

```
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    validate_and_repost_submissions()
  File "main.py", line 124, in validate_and_repost_submissions
    for submission in reddit.subreddit(reddit_subreddit_name).new(limit=reddit_post_limit):
  File "/usr/lib/python2.7/site-packages/praw/models/listing/generator.py", line 81, in next
    return self.__next__()
  File "/usr/lib/python2.7/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/lib/python2.7/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/lib/python2.7/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/usr/lib/python2.7/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/usr/lib/python2.7/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/usr/lib/python2.7/site-packages/prawcore/sessions.py", line 128, in _request_with_retries
    retries, saved_exception, url)
  File "/usr/lib/python2.7/site-packages/prawcore/sessions.py", line 94, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "/usr/lib/python2.7/site-packages/prawcore/sessions.py", line 128, in _request_with_retries
    retries, saved_exception, url)
  File "/usr/lib/python2.7/site-packages/prawcore/sessions.py", line 94, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "/usr/lib/python2.7/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 500 HTTP response
```

**Python3:**

```
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    validate_and_repost_submissions()
  File "main.py", line 124, in validate_and_repost_submissions
    for submission in reddit.subreddit(reddit_subreddit_name).new(limit=reddit_post_limit):
  File "/usr/local/lib/python3.6/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/local/lib/python3.6/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 442, in get
    data = self.request("GET", path, params=params)
  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 577, in request
    method, path, data=data, files=files, params=params
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 128, in _request_with_retries
    retries, saved_exception, url)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 94, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 128, in _request_with_retries
    retries, saved_exception, url)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 94, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 130, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 500 HTTP response
```

Anyway, thankyou for making this script.

**Comment by kerray** [comment]
You can see that it fails in Praw (python reddit library), so there's a problem connecting to Reddit. 

Please verify your settings (config.py) work - particularly the reddit client id, client secret and subreddit name - maybe you could try using Praw to connect to Reddit in the Python interactive shell to verify your settings work?

**Comment by RasyiidWho** [comment]
Hi Mr. Kerray, I found and this is my fault. I use "personal use script" mode in my app, but when I make another app with "web app" and look like this problem is fixed. But now, I found another problem 😅

```
ENTRY ID: d1t3v3 UPVOTES: 0 TITLE: thanks I hate SCP
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    validate_and_repost_submissions()
  File "main.py", line 140, in validate_and_repost_submissions
    if submission_offtopic(submission):
  File "main.py", line 58, in submission_offtopic
    return "offtopic" in submission.link_flair_text
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by RasyiidWho** [comment]
I found that this problem appear in new commit. I use old commit and it's working 😃

**Comment by RasyiidWho** [comment]
Also, can't post on facebook, it's says 

`FB ERROR Valid API versions are '2.10', '2.11', '2.12', '3.0', '3.1', '3.2', '3.3'`

So I try to change fb_graphapi_version in config.py, but I got this message

`FB ERROR 'GraphAPI' object has no attribute 'put_wall_post'`

*I use facebook-sdk version 2.0.0 and it's working..

**Comment by kerray** [comment]
the link_flair_text NoneType problem is from a recent commit, and it's a bug - should be fixed now

as to FB Graph API, I have 2.8 in my config and it seems to be working now... I'll take a look at it
